### ISSUE TITLE
No methods to close searchStream

### ISSUE THREAD

**Issue by traviscollins** [twitterdev/twitter-api-typescript-sdk#14]
According to the types description, there is no way to close a searchStream. 

### Expected behavior

There should be a searchStream(..) result object with the ability to close the stream. 

### Actual behavior

There is no close() method. 

### Steps to reproduce the behavior

Use the client.tweets.searchStream(...) interface.

**Comment by refarer** [comment]
Hey! The streaming endpoints are [async generators](https://javascript.info/async-iterators-generators) you can break out like this:

```typescript
let count = 0;
const stream = client.tweets.searchStream()
for await (const tweets of stream) {
  console.log(tweets);
  if (++count == 3) {
    break;
  }
}
```

**Comment by traviscollins** [comment]
Thanks @refarer  

The problem is that you can only break from within the loop. If you're running a search with infrequent tweet matches, then it can be a long time until the break is called. 

There needs to be a way to end the stream immediately from outside the loop.

**Comment by refarer** [comment]
Here's an example using [AbortController](https://nodejs.org/api/globals.html#class-abortcontroller)

```typescript
import { Client } from "twitter-api-sdk";
import AbortController from "abort-controller";

const client = new Client(process.env.BEARER_TOKEN);

const controller = new AbortController();

setTimeout(() => {
  controller.abort();
}, 5000);

const stream = client.tweets.searchStream(
  {
    "tweet.fields": ["author_id"],
  },
  { signal: controller.signal }
);

try {
  for await (const tweet of stream) {
    console.log(`Author ID: ${tweet.data.author_id}`);
  }
} catch (error) {
  console.log("Stream ended!");
}
```

It's available in Node 15 or you can use a package like above.
