### ISSUE TITLE
Error 400, Bad Request when using `authClient.requestAccessToken`

### ISSUE THREAD

**Issue by LightYagami200** [twitterdev/twitter-api-typescript-sdk#15]
I'm getting Error 400, Bad Request when trying to use `authClient.requestAccessToken(code)`

### Expected behavior

I should get the token and be able to make requests on behalf of logged in user.

### Actual behavior

I get this error message

![image](https://user-images.githubusercontent.com/35832598/171259425-b989ab3b-d3f1-4be4-92c7-503aeddbed5f.png)

### Steps to reproduce the behavior

Generate auth url with this code:
```
const authUrl = authClient.generateAuthURL({
  code_challenge_method: 's256',
  state: 'STATE',
});
```

Visit that url - authenticate with twitter and use the code to get access token:
```
await twitterAuthClient.requestAccessToken(code as string);
```

Now it throws that error

**Comment by refarer** [comment]
Hey, I am going to improve the error given here. You probably just need some more detail in order to find out whats going wrong.

**Comment by mort3za** [comment]
Did you find any solution?  
This is the error message I get when I follow the example code above:
```
Missing required parameter [code_verifier].
```

**Comment by LightYagami200** [comment]
> Did you find any solution?  
> 
> This is the error message I get when I follow the example code above:
> 
> ```
> 
> Missing required parameter [code_verifier].
> 
> ```
> 
> 
> 
> 

I managed to solve it by creating a fork and fixing that bug myself (you can find the fork in my gh profile if you want)
