### ISSUE TITLE
Examples fail to authorize

### ISSUE THREAD

**Issue by equal-l2** [twitterdev/twitter-api-typescript-sdk#38]
I'm not able to authorize through `http://127.0.0.1:3000/login`.
(I didn't test `bearer` variants as I don't need to use them)

### Expected behavior

`http://127.0.0.1:3000/login` should redirect me to the twitter authorization screen with appropriate parameters.

### Actual behavior

Something is wrong with the parameters, the screen says "Something went wrong".

### Steps to reproduce the behavior

1. Run `npm install` in the examples directory, with `"ts-node": "^10.9.1"` (the original spec for ts-node didn't work)
2. Create `.env` as following:
```shell
CLIENT_ID=<REDACTED>
CLIENT_SECRET=<REDACTED>
```
3. Run any example and jump to the login URL.

**Comment by roj1512** [comment]
What is the callback URL in your Twitter OAuth2 settings?

**Comment by equal-l2** [comment]
Thank you for pointing out the callback URL, I forgot to add the URL used by examples.
After setting the URL, everything goes well!

Thank you again for your help!

**Comment by roj1512** [comment]
You’re welcome 😉
