### ISSUE TITLE
Filtered-stream example not working OOB

### ISSUE THREAD

**Issue by maggz69** [twitterdev/twitter-api-typescript-sdk#9]
Twitter Filtered stream example when making use of rules does not send the rules to Twitter before initiating the stream

### Expected behavior

Running the Twitter Sample Srteam SDK

### Actual behavior

Request fails with *409, Conflict*
Body is `{"title":"ConnectionException","detail":"You must define rules using the POST /2/tweets/search/stream/rules endpoint before connecting to filtered stream.","connection_issue":"RuleConfigurationIssue","type":"https://api.twitter.com/2/problems/streaming-connection"}`

### Steps to reproduce the behavior

Using a bearer token, run the filtered-stream.ts example as is on [the examples page](https://github.com/twitterdev/twitter-api-typescript-sdk/blob/main/examples/filtered-stream.ts)

**Comment by andypiper** [comment]
I think this is due to the `dry_run` being set in the sample. Can you try changing `dry_run: true` to `dry_run: false` and re-running the sample?

**Comment by maggz69** [comment]
Thanks, removing the `dry_run:true` param does allow the code to run. @refarer , thanks for the PR that helps make onboarding much more efficient in this regards
